language: objective-c  #1
osx_image: xcode10 #2
xcode_project: CaseContainer.xcodeproj #3
xcode_scheme: Example #4
xcode_sdk: iphonesimulator12.0 #5

jobs:
  include:
    - script: xcodebuild build test -project CaseContainer.xcodeproj -scheme Example -destination "platform=iOS Simulator,name=iPhone 8,OS=12.0" -enableCodeCoverage YES 
      after_script: bash <(curl -s https://codecov.io/bash) -J 'CaseContainer'